#!/usr/bin/env python3
"""
Fleet Config Generator for OpenManus Containerized Agent Swarm.

This script generates per-agent configuration directories, OpenManus config.toml
files, and a docker-compose.yml for the full 8-service fleet (6 agents +
fleet-api + dashboard).

Usage:
    python generate_fleet.py
"""

from __future__ import annotations

import os
import stat
import sys
from pathlib import Path
from typing import Final

# ── FLEET DEFINITION ──────────────────────────────────────────────────────────
# Each agent gets a dedicated OpenRouter free-tier model.  Keep this table in
# sync with the SPEC.md agent roster.

FLEET: Final[list[dict[str, str]]] = [
    {
        "id": "prospector",
        "name": "PROSPECTOR",
        "role": "Lead research & discovery",
        "model": "meta-llama/llama-4-maverick:free",
    },
    {
        "id": "forge",
        "name": "FORGE",
        "role": "Code generation & building",
        "model": "google/gemini-2.5-pro-exp-03-25:free",
    },
    {
        "id": "lens",
        "name": "LENS",
        "role": "Review, audit & QA",
        "model": "deepseek/deepseek-chat-v3-0324:free",
    },
    {
        "id": "copywriter",
        "name": "COPYWRITER",
        "role": "Content & copy generation",
        "model": "qwen/qwen3-235b-a22b:free",
    },
    {
        "id": "herald",
        "name": "HERALD",
        "role": "Outreach & communication",
        "model": "nvidia/nemotron-4-340b-instruct:free",
    },
    {
        "id": "ledger",
        "name": "LEDGER",
        "role": "Logging, tracking & analytics",
        "model": "moonshotai/kimi-k2:free",
    },
]

# ── TEMPLATES ─────────────────────────────────────────────────────────────────

CONFIG_TOML_TEMPLATE: Final[str] = """# OpenManus configuration -- auto-generated by generate_fleet.py
# Agent: {name} ({id})

[llm]
api_key = "{api_key}"
model = "{model}"
base_url = "https://openrouter.ai/api/v1"

[agent]
name = "{name}"
role = "{role}"
heartbeat_url = "{heartbeat_url}"
"""

DOCKER_COMPOSE_TEMPLATE: Final[str] = """# Auto-generated by generate_fleet.py
# OpenManus Containerized Agent Swarm -- 8 services

services:
{fleet_services}

  fleet-api:
    build: ./fleet-api
    container_name: fleet-api
    ports:
      - "8800:8800"
    environment:
      - DATABASE_URL=sqlite:///fleet.db
    volumes:
      - fleet_db:/app/data
    networks:
      - swarm-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8800/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://fleet-api:8800
    depends_on:
      fleet-api:
        condition: service_healthy
    networks:
      - swarm-net

volumes:
  fleet_db:

networks:
  swarm-net:
    driver: bridge
"""

AGENT_SERVICE_TEMPLATE: Final[str] = """  {id}:
    build:
      context: ./agents
      dockerfile: Dockerfile
    image: agent-base
    container_name: {id}
    environment:
      - AGENT_ID={id}
      - AGENT_NAME={name}
      - AGENT_ROLE={role}
      - HEARTBEAT_URL=http://fleet-api:8800/heartbeat
      - OPENROUTER_API_KEY=${{OPENROUTER_API_KEY}}
    volumes:
      - ./agents/{id}/config.toml:/app/config.toml:ro
    depends_on:
      fleet-api:
        condition: service_healthy
    networks:
      - swarm-net
    restart: unless-stopped
"""


# ── HELPERS ───────────────────────────────────────────────────────────────────


def ensure_dir(path: Path) -> None:
    """Create a directory if it does not already exist."""
    path.mkdir(parents=True, exist_ok=True)


def write_file(path: Path, content: str) -> None:
    """Write *content* to *path* with UTF-8 encoding."""
    path.write_text(content, encoding="utf-8")


def make_executable(path: Path) -> None:
    """Add executable permission to *path*."""
    current = path.stat().st_mode
    path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def get_env_or_prompt(var_name: str, prompt_text: str) -> str:
    """Return the value of *var_name* from the environment, or prompt the user."""
    value = os.environ.get(var_name, "").strip()
    if not value:
        value = input(f"{prompt_text}: ").strip()
    if not value:
        print(f"[ERROR] {var_name} is required.", file=sys.stderr)
        sys.exit(1)
    return value


# ── GENERATORS ────────────────────────────────────────────────────────────────


def generate_agent_config(
    agent: dict[str, str], api_key: str, heartbeat_url: str
) -> str:
    """Render a config.toml for a single agent.

    Parameters
    ----------
    agent:
        Dictionary with ``id``, ``name``, ``role``, and ``model`` keys.
    api_key:
        OpenRouter API key to embed in the config.
    heartbeat_url:
        Full URL where the agent should POST heartbeats.

    Returns
    -------
    str
        Rendered TOML configuration.
    """
    return CONFIG_TOML_TEMPLATE.format(
        id=agent["id"],
        name=agent["name"],
        role=agent["role"],
        model=agent["model"],
        api_key=api_key,
        heartbeat_url=heartbeat_url,
    )


def generate_docker_compose(fleet: list[dict[str, str]]) -> str:
    """Render the root docker-compose.yml for all 8 services.

    Parameters
    ----------
    fleet:
        List of agent dictionaries (see :data:`FLEET`).

    Returns
    -------
    str
        Complete docker-compose YAML content.
    """
    fleet_blocks = "\n".join(AGENT_SERVICE_TEMPLATE.format(**a) for a in fleet)
    return DOCKER_COMPOSE_TEMPLATE.format(fleet_services=fleet_blocks)


# ── MAIN ──────────────────────────────────────────────────────────────────────


def main() -> None:
    """Run the fleet generator."""
    print("=" * 60)
    print("  OpenManus Containerized Agent Swarm -- Fleet Generator")
    print("=" * 60)

    # Resolve paths relative to this script
    script_dir = Path(__file__).resolve().parent
    agents_dir = script_dir / "agents"

    # Gather required configuration
    openrouter_key = get_env_or_prompt(
        "OPENROUTER_API_KEY", "Enter OpenRouter API key"
    )
    heartbeat_url = os.environ.get("FLEET_API_URL", "http://fleet-api:8800").rstrip(
        "/"
    )
    heartbeat_url = f"{heartbeat_url}/heartbeat"

    # 1. Create per-agent directories and configs
    print("\n[1/3] Creating agent directories & configs ...")
    for agent in FLEET:
        agent_dir = agents_dir / agent["id"]
        ensure_dir(agent_dir)

        config_path = agent_dir / "config.toml"
        config_content = generate_agent_config(agent, openrouter_key, heartbeat_url)
        write_file(config_path, config_content)

        print(f"    agents/{agent['id']}/config.toml")

    # 2. Generate docker-compose.yml
    print("\n[2/3] Generating docker-compose.yml ...")
    compose_path = script_dir / "docker-compose.yml"
    write_file(compose_path, generate_docker_compose(FLEET))
    print(f"    {compose_path}")

    # 3. Ensure agents/run.sh is executable
    run_sh = agents_dir / "run.sh"
    if run_sh.exists():
        make_executable(run_sh)
        print("    agents/run.sh is executable")

    # Summary table
    print("\n[3/3] Fleet Summary")
    print("-" * 60)
    print(f"{'Agent':<14} {'Name':<12} {'Role':<28} {'Model'}")
    print("-" * 60)
    for agent in FLEET:
        model_short = agent["model"].split(":")[0].split("/")[-1]
        print(
            f"{agent['id']:<14} {agent['name']:<12} {agent['role']:<28} {model_short}"
        )
    print("-" * 60)
    print(f"\nTotal agents : {len(FLEET)}")
    print(f"Services     : {len(FLEET) + 2} (6 agents + fleet-api + dashboard)")
    print(f"\nNext step:  docker compose up -d --build")
    print("=" * 60)


if __name__ == "__main__":
    main()
